### ISSUE TITLE
Apply MIT license to codebase

### ISSUE THREAD

**Issue by Cloven** [bucko909/erlcapnp#1]
Hi!  There doesn't appear to be an explicit LICENSE file that I can find.  What license is applicable, if any?

**Comment by bucko909** [comment]
Um, pretty much any I guess. I tend to prefer BSD-style. Would FreeBSD suit your needs?

I should probably _check_ with my employer, as this was developed partially on their time with permission to upload to Github, but no stated license.

**Comment by Cloven** [comment]
The license is up to you, of course; I think 3-clause BSD or MIT would be "best" but you should definitely check with your employer.

**Comment by bucko909** [comment]
MIT seems the consensus. I'll have to look at what I have to do to make that happen (I guess paste the license into each file), but I'll probably get around to it next week.

**Comment by bucko909** [comment]
Done!

**Comment by Cloven** [comment]
nice, thank you!
